### ISSUE TITLE
Outdated Dependency Detection

### ISSUE THREAD

**Issue by Henni** [nextcloud/3rdparty#36]
Updating the versioneye badge would allow us to detect outdated dependencies easily.
[![Dependency Status](https://www.versioneye.com/user/projects/576c043fcd6d510048bab256/badge.svg?style=flat-square)](https://www.versioneye.com/user/projects/576c043fcd6d510048bab256)
Currently it is stuck at some old commit (Last checked at "Jul 15, 2016 - 18:26" )

To make the badge and the results of versioneye meaningful it also might make sense to add the supported php versions to the composer.json. This way only updates are shown that still support php version 5.6 (this is the latest version we support, right?)

**Comment by MorrisJobke** [comment]
> Currently it is stuck at some old commit (Last checked at "Jul 15, 2016 - 18:26" )

Somehow the automatic re-parse didn't happen. I just triggered it.

**Comment by splitt3r** [comment]
VersionEye will shut down: https://blog.versioneye.com/2017/10/26/the-start-of-a-new-journey/

**Comment by ChristophWurst** [comment]
Hey, how about we enable [dependabot](https://app.dependabot.com) for this repo? I'm using it for some personal projects and the 2fa apps. It checks the `composer.json` file once a day and submits pull requests for all outdated dependencies. It then even detects changes of the master brach and rebases those PRs.

cc @rullzer

**Comment by ChristophWurst** [comment]
FYI this is what it looks like when dependabot updates a dependency: https://github.com/nextcloud/twofactor_totp/pull/211

Note that you can even see what has changed (commit range and changelog if available).

**Comment by rullzer** [comment]
I'm not sure it does exactly what we need. As we don't just need the updated json file but ship the whole dependencies. But lets look at this over christmas or so

**Comment by ChristophWurst** [comment]
@rullzer I see. So it is actually is unclear whether dependabot will also commit the code of updated libs. I'll give it a quick test run in a forked repo.

**Comment by ChristophWurst** [comment]
Alright, so apparently it does not yet update dependency sources: https://github.com/dependabot/feedback/issues/62#issuecomment-351370473

**Comment by rullzer** [comment]
I would suggest to just enable dependabot here. It can still create the simple PR's. Then we at least know there is stuff to upgrade.

As it will require manual work anyway to update the 3rdparty ref etc.

**Comment by ChristophWurst** [comment]
> As it will require manual work anyway to update the 3rdparty ref etc.

Well, one *could* add a CI job to commit the package changes and push them back to github. I've heard people actually [do](https://github.com/ChristophWurst/nextcloud_composer/blob/master/push.sh) [that](https://github.com/ChristophWurst/nextcloud_composer/blob/master/.travis.yml).

**Comment by rullzer** [comment]
@ChristophWurst well well well looks like I found a volunteer to fix it all ;)

**Comment by JonathanTreffler** [comment]
It might be easier with Github Action than Travis
