### ISSUE TITLE
NC18RC1, php7.4 report

### ISSUE THREAD

**Issue by jookk** [nextcloud/3rdparty#376]
The behavior of unparenthesized expressions containing both '.' and '+'/'-' will change in PHP 8: '+'/'-' will take a higher precedence at /var/www/nextcloud/3rdparty/sabre/vobject/lib/Recur/RRuleIterator.php#423

The behavior of unparenthesized expressions containing both '.' and '+'/'-' will change in PHP 8: '+'/'-' will take a higher precedence at /var/www/nextcloud/3rdparty/sabre/vobject/lib/Recur/RRuleIterator.php#357

nginx 1.17.7
php7.4-fpm
debian 10

**Comment by jookk** [comment]
Trying to access array offset on value of type null at /var/www/nextcloud/3rdparty/leafo/scssphp/src/Compiler.php#5230

**Comment by J0WI** [comment]
See also https://github.com/nextcloud/server/issues/18996

**Comment by J0WI** [comment]
Duplicate of https://github.com/nextcloud/server/issues/16574
