### ISSUE TITLE
sabre/dav is looking for a new maintainer

### ISSUE THREAD

**Issue by mbiebl** [nextcloud/3rdparty#48]
This is just a heads up that Evert Pot, the author of sabre/dav, has stopped working on it:
https://evertpot.com/sabredav-eol/

Since nextcloud relies on sabre/dav heavily for it's calendar/contacts support, it might be reasonable for the nextcloud project to get involved in the maintenance of sabre/dav. Evert seems to be looking for people who can take over.
https://evertpot.com/sabredav-eol/#comment-3194634289

**Comment by MorrisJobke** [comment]
We are already in contact with Evert and his team

**Comment by mbiebl** [comment]
Ok, good to know. Can you share any details yet?
