### ISSUE TITLE
Update Guzzle

### ISSUE THREAD

**Issue by sysmoh** [nextcloud/3rdparty#49]
Hey, currently Guzzle is at version 5.3, is it possible to upgrade it to the latest version ? (6.2)
This would allow us to create custom apps that can use this version, and packages based on it (IE League's Oauth2 client).

Thanks a lot!

**Comment by MorrisJobke** [comment]
cc @rullzer @LukasReschke

**Comment by rullzer** [comment]
There was a reason we had the legacy one around.... I can't remember it currently...

**Comment by rullzer** [comment]
Ah right it is because of the php-opencloud thingy. Wich we use for the swift objectstore.

@icewind1991 is there a reason that is not an app?

**Comment by rullzer** [comment]
Ah no... that is why we still have guzzle/guzzle... let me see if I can upgrade guzzlehttp/guzzle

**Comment by rullzer** [comment]
Ok this won't be very easy. As signigicat stuff changed from 5 to 6. So this will be a big change. I prefer to do this easly in a release cycle. since it will require updating a lot of stuff.

**Comment by MorrisJobke** [comment]
I thought one big problem was, that 6 dropped 5.6 IIRC.

**Comment by MorrisJobke** [comment]
> I thought one big problem was, that 6 dropped PHP 5.6 support IIRC.

Mmmh ... it seems to support PHP 5.5.+

**Comment by rullzer** [comment]
@MorrisJobke well that was the reason why before we never upgraded... since we still supported 5.4 back then.

**Comment by marcelklehr** [comment]
Just ran into this as well. Is there any way I can still use a dependency that requires guzzle v6.x?

**Comment by marcelklehr** [comment]
:joy:
