### ISSUE TITLE
Huge Performance Difference between SabreDAV 3.2.x and NextCloud

### ISSUE THREAD

**Issue by Offerel** [nextcloud/3rdparty#54]
I have noticed that there is a very huge Performance Difference between pure SabreDAV 3.2.x and NextCloud 11. For example, if i have NextCloud 11 and SabreDAV 3.20 installed on the same Server, it takes 40 - 70 seconds to upload a 300kb file via WebDAV with NextCloud. The same file will Upload to SabreDAV via WebDAV in 6 seconds. I have made no optimization in SabreDAV. The only difference is, that i use a other Subdomain for the SabreDAV Installation and another  Subdomain for NextCloud 11.

What could be the reason for this? Are there some more operations in NextCloud, specially some I/O Operations as in SabreDAV itself? Can this operations be minimized or completely disabled?

**Comment by MorrisJobke** [comment]
cc @icewind1991 @rullzer

**Comment by creopard** [comment]
Are you hitting nextcloud's brute force protection?
https://help.nextcloud.com/t/slow-webdav-performance/11255
