### ISSUE TITLE
Replacement for phpass?

### ISSUE THREAD

**Issue by poVoq** [nextcloud/3rdparty#56]
Owncloud used to hash&salt passwords stored in the database with phpass a while ago. What was used to replace this? I am looking to access the sql database with an external program (simplesamlphp as idp) and would need to know how the passwords are stored in Nextcloud.

**Comment by MorrisJobke** [comment]
> I am looking to access the sql database with an external program (simplesamlphp as idp)

Don't do that. We can't guarantee that the DB schema will not be updated.

You could use the user_saml app to authenticate the other way around. ;)

cc @LukasReschke

**Comment by LukasReschke** [comment]
We don't support accessing the user database directly. The current implementation uses bcrypt but there are also legacy hashes etc.

**Comment by poVoq** [comment]
I understand that it is un-supported, but is it really such a problem? I would like to store and administer users through Nextcloud, while allowing external services to authenticate with SAML and this seems like the best solution. In fact I am even thinking of allowing "circular" authentification with user_saml, but completly going with an external user-database for simpleSAML breaks a lot of other Nextcloud app functionality (such as XMPP cloud auth etc.).
