### ISSUE TITLE
Bump aws-sdk-php

### ISSUE THREAD

**Issue by mss** [nextcloud/3rdparty#71]
Hi there,

I am currently looking at some odd behaviour of the NC13 S3 ObjectStore with the multipart upload introduced in nextcloud/server#6602 in combination with minio.

Just to be sure that this isn't an issue with the aws-sdk-php version, would it be possible to bump the SDK from the currenty used version 3.35.2 to the latest version (3.39.2 [right now](https://github.com/aws/aws-sdk-php/blob/master/CHANGELOG.md)) or is there some reason not to?

**Comment by MorrisJobke** [comment]
cc @icewind1991

**Comment by mss** [comment]
Another thing I forgot to add and the reason I opened this issue: minio's own [test suite](https://github.com/minio/mint) again aws-sdk-php don't show this issue but I didn't dig further yet to see if this is due to a changed AWS SDK or an incorrect test. I'll have a closer look when I have some spare time.

**Comment by rullzer** [comment]
@mss please try NC15. NC13 is already quite old and as a general rule we opnly update security issues there in 3rdparty deps.
