### ISSUE TITLE
"The each() function is deprecated" from scssphp, which is fixed upstream

### ISSUE THREAD

**Issue by yan12125** [nextcloud/3rdparty#72]
The following message jumps out after upgrading to PHP 7.2:
```
The each() function is deprecated. This message will be suppressed on further calls at /usr/share/webapps/nextcloud/3rdparty/leafo/scssphp/src/Node/Number.php#293
```
Apparently this is already fixed in upstream (https://github.com/leafo/scssphp/commit/494c09f0c08261265ddca4ca51c51670e01680c4), and the fixed is included in scssphp 0.7.1+. Please consider bump it, thanks!

EDIT: I'm using Nextcloud 13.0.0 beta 3 + php 7.2.0

**Comment by MorrisJobke** [comment]
cc @rullzer @skjnldsv Should we bump the scssphp version from our 0.6.6 to 0.7.1+? I would say so and include it also in the 13.0.0 release for 7.2 compatibility.

**Comment by MorrisJobke** [comment]
Looking at the diff I would do this: https://github.com/leafo/scssphp/compare/v0.6.6...v0.7.2

Let me prepare a PR.

**Comment by MorrisJobke** [comment]
PR is in #73
