### ISSUE TITLE
Update doctrine/dbal to 2.6.x

### ISSUE THREAD

**Issue by LorbusChris** [nextcloud/3rdparty#82]
The patch seems to have been merged upstream and released in 2.6.0 (current v2.6.3):
https://github.com/doctrine/dbal/pull/2422

(in patches.txt)
```
- Doctrine: fix error handling for not null columns on some mysql servers https://github.com/doctrine/dbal/pull/2422
```

**Comment by LorbusChris** [comment]
Any movement on this? Should I create a PR?

**Comment by LorbusChris** [comment]
Oh I see there's a bot for that now! Maybe one can re-trigger it for those outdated deps that don't get new releases regularily?

**Comment by MorrisJobke** [comment]
cc @rullzer
