### ISSUE TITLE
Switch to DeepDiver1975/PHPZipStreamer

### ISSUE THREAD

**Issue by LorbusChris** [nextcloud/3rdparty#84]
As of https://github.com/McNetic/PHPZipStreamer/pull/39 the ZipStreamer repo seems to be unmaintained.

Use updated fork from DeepDiver1975 instead:
https://github.com/DeepDiver1975/PHPZipStreamer

**Comment by MorrisJobke** [comment]
Afaik @rullzer is already working on this :)

**Comment by rullzer** [comment]
Working is a strong word. I first have to make the test pass :see_no_evil:

**Comment by andreicociuba** [comment]
would this solve https://github.com/McNetic/PHPZipStreamer/issues/38 ?
