### ISSUE TITLE
Online video player for many types of video files

### ISSUE THREAD

**Issue by Tas-sos** [nextcloud/3rdparty#9]
Excuse me, if opening this topic in the wrong place. ( _If i do wrong, where else can we talk about that ?_ )

So what we would like to discuss, has to do with the possibility support online video player for video player for many types of video files.
So far, you can see online only .mp4 video , i do wrong ?
That this is possible is amazing, but I think all of us we would like a more flexible online video player.

Because i don't know, that's why i'm asking you, how easy or difficult it would be to try to do something like that ?

There is already the feature for .mp4 video to add .mkv for example, is difficult?
And if we can do the first steps , it would be perfect for me to support subtitles.

Thank you very much for your time!
I am open to any suggestions :)

P.S. : Sorry for my bad English!

**Comment by MorrisJobke** [comment]
This is usually being accomplished by the shipped video player: https://github.com/nextcloud/files_videoplayer

Could you open specific issues, what files didn't work? Also also in which cases? Public shared folders or as logged in user. 

A related ticket for the general issue is https://github.com/nextcloud/server/issues/604

This repo here is only for 3rdparty dependencies and is the wrong place. But don't worry we will try to accomplish the described stuff in the above linked ticket :)
